name: Web Application Develop Server CI/CD

on:
  pull_request:
    branches: ["main"]
    types:
      - opened
      - synchronize
  push:
    branches: ["main"]

env:
  CONTAINER_NAME: teolmungchi

jobs:
  CI:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.18.0

      - name: Add .env
        run: |
          echo "${{ secrets.ENV }}" > ./.env

      - name: Install Dependencies
        run: npm install

      - name: Build NestJS Application
        run: npm run build

      - name: Login to Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        if: github.event_name == 'push'
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        if: github.event_name == 'push'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_ID }}/${{ env.CONTAINER_NAME }}:${{ github.run_number }},${{ secrets.DOCKER_ID }}/${{ env.CONTAINER_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  CD:
    needs: [CI]
    if: github.event_name == 'push'  # push 이벤트에서만 CD 실행
    runs-on: ubuntu-20.04
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.REMOTE_HOST_DEV }}
          username: ${{ secrets.REMOTE_USERNAME_DEV }}
          key: ${{ secrets.REMOTE_SSH_KEY_DEV }}
          port: ${{ secrets.REMOTE_PORT_DEV }}
          script: |
            docker login -u ${{ secrets.DOCKER_ID }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker stop ${{ env.CONTAINER_NAME }} || true
            docker rm ${{ env.CONTAINER_NAME }} || true
            docker image rm ${{ secrets.DOCKER_ID }}/${{ env.CONTAINER_NAME }} || true

            echo "${{ secrets.ENV }}" > /home/${{ secrets.REMOTE_USERNAME_DEV }}/.env

            docker run -d -p 3000:3000 \
              --name ${{ env.CONTAINER_NAME }} \
              --network tmc-network \
              --env-file /home/${{ secrets.REMOTE_USERNAME_DEV }}/.env \
              --restart=unless-stopped \
              --log-opt max-size=10m --log-opt max-file=3 \
              ${{ secrets.DOCKER_ID }}/${{ env.CONTAINER_NAME }}:${{ github.run_number }}

            docker image prune -f